WEATHER SENSOR DATA ANALYSIS

This project analyzes synthetic weather sensor data (temperature and humidity) for three Nigerian cities -Lagos, Abuja, and Kano - over a 4-day period.
The dataset is stored as a numpy array with the following structure
Axis 0 - City (0: Lagos, 1: Abuja, 2: Kano)
Axis 1 - Day(0: Day 1, 1: Day 2, 2: Day 3, 3: Day 4)
Axis 2 - Measurement(0: Temperature, 1: Humidity(%))
By simulating the sensor readings, the project demonstrates how multidiensional data is extracted, manipulated and analyzed using Numpy

What I did
1. Loaded and structured weather sensor readings into a (3, 4, 2) Numpy array
2. Extracted temperature and humidity readings using slicing and indexing
3. Identified days with temperature > 30 degree celsius and cities eith humidity < 50%, cleaned up result for readability
4. Created separate arrays for temperature (3, 4) and humidity (3, 4)
5. Computed sorted temperatures, avg per city, and found the day with highest temperature in Abuja
6. Determined the city with the lowest overall humidity
7. Documented clear mappings for City - Day - Measurement for reproducibility

In [1]:
import numpy as np
# Example weather_data ( city * day * measurement)
# Shape: (3, 4, 2)
# 3 cities, 4 days , 2 measurements (Temp, Humidity)
weather_data = np.array([
    # Lagos
    [[29, 70], [32, 65], [31, 60], [28, 75]],
    # Abuja
    [[26,55], [34,50], [30, 48], [29, 52]],
    # Kano
    [[35, 40], [33, 42], [36, 38], [34, 45]]
])
#-----------------------------
# 1. Shape, Size, Dimensions
#-----------------------------
print("Shape:", weather_data.shape)
print("Size:", weather_data.size)
print("Dimensions:", weather_data.ndim)

print("\nAxis meaning:")
print("Axis 0: City (0: Lagos, 1: Abuja, 2: Kano)")
print("Axis 1: Day (0: Day1, 1: Day2, 2: Day3, 3: Day4)")
print("Axis 2: Measurement (0: Temp, 1: Humidity)")

#--------------------------------------------
# 2. Slicing
#--------------------------------------------
# All temperatures for Lagos
lagos_temps = weather_data[0, 0:, 0]
print("\nLagos Temperatures:", lagos_temps)

# Humidity values for Day 2 (axis =1, index= 1) across all cities
day2_humidity = weather_data[:, 1, 1]
print("Day 2 Humidity(all cities):", day2_humidity)

#Slice data for Kano (city = 2) on day 3 (day=2)
kano_day3 = weather_data[2, 2, :]
print("Kano Day 3 (Temp & Humidity):", kano_day3)

#-----------------------------------------
# 3. Fancy indexing
#-----------------------------------------
selected_temps = weather_data[[0, 1, 2], [0, 1, 2], 0]
print("\nSelected Temps (Lagos D1, Abuja D2, Kano D3):", selected_temps)

#--------------------------------------------
# 4. Conditions
#--------------------------------------------
# Days when temp is > 30
days_temp_gt30 = np.where(weather_data[:, :, 0] > 30)
print("Temp > 30 degree Celsius (city, day):", list(zip(days_temp_gt30[0].tolist(), days_temp_gt30[1].tolist())))

#--------------------------------------------------
# Cities with humidity less than 50%
cities_humidity_1t50 = np.where(weather_data[:, :, 1] < 50)
print("Humidity < 50% (city, day):", list(zip(cities_humidity_1t50[0].tolist(), cities_humidity_1t50[1].tolist())))

#---------------------------------------------------------
# 5. Stacking temp and humidity separately
#----------------------------------------------------------
temp_data = weather_data[:, :, 0]
humidity_data = weather_data[:, :, 1]

print("\nTemp Data shape:", temp_data.shape)
print(temp_data)
print("Humidity data shape:", humidity_data.shape)
print(humidity_data)

#--------------------------------------------------
# 6. Sorting & max
#--------------------------------------------------
sorted_temps = np.sort(temp_data.flatten())
print("\nAll Temperatures Sorted:", sorted_temps)

# Day with highest in Abuja (city =1)
abuja_temps = temp_data[1, :]
highest_day_abuja = np.argmax(abuja_temps)
print("Abuja Temps:", abuja_temps)
print("Day with highest temp in Abuja:", highest_day_abuja+1, "with", abuja_temps[highest_day_abuja], "degree Celsius")

#----------------------------------------------------
# 7. Average temperature per city
#----------------------------------------------------
avg_temp_city = np.mean(temp_data, axis=1)
print("\nAverage Temp per city:", avg_temp_city)

#-------------------------------------------------
# 8. City with overall lowest humidity
#------------------------------------------------
avg_humidity_city = np.mean(humidity_data, axis=1)
lowest_humidity_city = np.argmin(avg_humidity_city)
cities = ["Lagos", "Abuja", "Kano"]

print("\nAverage Humidity per city:", avg_humidity_city)
print("city with lowest humidity:", cities[lowest_humidity_city])
      

Shape: (3, 4, 2)
Size: 24
Dimensions: 3

Axis meaning:
Axis 0: City (0: Lagos, 1: Abuja, 2: Kano)
Axis 1: Day (0: Day1, 1: Day2, 2: Day3, 3: Day4)
Axis 2: Measurement (0: Temp, 1: Humidity)

Lagos Temperatures: [29 32 31 28]
Day 2 Humidity(all cities): [65 50 42]
Kano Day 3 (Temp & Humidity): [36 38]

Selected Temps (Lagos D1, Abuja D2, Kano D3): [29 34 36]
Temp > 30 degree Celsius (city, day): [(0, 1), (0, 2), (1, 1), (2, 0), (2, 1), (2, 2), (2, 3)]
Humidity < 50% (city, day): [(1, 2), (2, 0), (2, 1), (2, 2), (2, 3)]

Temp Data shape: (3, 4)
[[29 32 31 28]
 [26 34 30 29]
 [35 33 36 34]]
Humidity data shape: (3, 4)
[[70 65 60 75]
 [55 50 48 52]
 [40 42 38 45]]

All Temperatures Sorted: [26 28 29 29 30 31 32 33 34 34 35 36]
Abuja Temps: [26 34 30 29]
Day with highest temp in Abuja: 2 with 34 degree Celsius

Average Temp per city: [30.   29.75 34.5 ]

Average Humidity per city: [67.5  51.25 41.25]
city with lowest humidity: Kano
